name: Create Release
on:
 workflow_dispatch:

jobs:
 release:
  runs-on: ubuntu-latest
  steps:

   - name: Checkout Repository
     uses: actions/checkout@v4
     with:
       fetch-depth: 0

   - name: Setup GitVersion
     uses: gittools/actions/gitversion/setup@a94a3b62ee018ef5346cb08fd0d63d93811fe691
     with:
       versionSpec: '5.x'

   - name: Determine Version
     id: gitversion
     uses: gittools/actions/gitversion/execute@a94a3b62ee018ef5346cb08fd0d63d93811fe691

    # action doesn't parse dependency files but instead queries github API and thus needs the repository name
   - name: Generate dependencies action
     uses: thedave42/generate-dependencies-csv-action@f33ebe876bf2441535ae36dfddbe126f8ea4c26a
     with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
       repo-names: ${{ github.event.repository.name }}

   - name: Generate checksums
     uses: jmgilman/actions-generate-checksum@v1
     with:
      output: ${{ steps.gitversion.outputs.semVer }}-sha256.txt
      method: sha256
      patterns: |
       *.zip
       *-dependency-list.csv

   - name: Release
     uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
     with:
      name: PSA.Artis2 ${{ steps.gitversion.outputs.semVer }}
      tag_name: ${{ steps.gitversion.outputs.semVer }}
      target_commitish: ${{ github.sha }}
      generate_release_notes: true
      fail_on_unmatched_files: true
      prerelease: ${{ steps.gitversion.outputs.preReleaseNumber != null }}
      files: |
        *-dependency-list.csv
        ${{ steps.gitversion.outputs.semVer }}-sha256.txt